spring:
  profiles:
    active: dev

task:
  nvidiaSmiPath: c:/mine/libnvidia-smi.exe

behash:
  homePath: C:/mine/lib/behash


limit:
  limitFile: C:/mine/lib/limit.exe


logging:
  file:
    name: logs/SmartMine.log